"""
Seed batch 2 — species 26–50
Adds 25 species to bring the database from 25 to 50.

Run with: python3 seed_species_batch2.py
"""

import sys
import os
import uuid

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from app.database import SessionLocal
from app.models.species import Species, CareLevel


SPECIES_DATA = [
    # ───────────────────────────────────────────────
    # NEW WORLD — BEGINNER TERRESTRIALS
    # ───────────────────────────────────────────────
    {
        "scientific_name": "Brachypelma emilia",
        "common_names": ["Mexican Red Leg"],
        "genus": "Brachypelma",
        "family": "Theraphosidae",
        "care_level": CareLevel.BEGINNER,
        "temperament": "docile",
        "native_region": "Mexico (Pacific coast, Jalisco to Guerrero)",
        "adult_size": "5-6 inches",
        "growth_rate": "slow",
        "type": "terrestrial",
        "temperature_min": 72,
        "temperature_max": 82,
        "humidity_min": 60,
        "humidity_max": 70,
        "enclosure_size_sling": 'Small vial or 2x2x3"',
        "enclosure_size_juvenile": '5x5x5"',
        "enclosure_size_adult": '10x10x8" or 5-10 gallon tank',
        "substrate_depth": "3-4 inches",
        "substrate_type": "dry coco fiber or peat moss mix",
        "prey_size": "Appropriately sized prey (up to 2/3 body length)",
        "feeding_frequency_sling": "Every 4-5 days",
        "feeding_frequency_juvenile": "Once per week",
        "feeding_frequency_adult": "Every 1-2 weeks",
        "water_dish_required": True,
        "webbing_amount": "light",
        "burrowing": True,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Mexican Red Leg** — Distinguished by its black body with orange-red patella joints and a distinctive orange carapace pattern. Very similar in care to *B. hamorii*. One of the original 'classic' pet tarantulas. CITES Appendix II listed. Most individuals in the hobby are captive bred. Extremely slow-growing — slings can take 8+ years to reach adulthood. Docile and generally reluctant to flick hairs without good reason. Keep the enclosure dry with one corner allowed to stay slightly moist.",
        "is_verified": True,
    },
    {
        "scientific_name": "Brachypelma auratum",
        "common_names": ["Mexican Flame Knee"],
        "genus": "Brachypelma",
        "family": "Theraphosidae",
        "care_level": CareLevel.BEGINNER,
        "temperament": "docile",
        "native_region": "Mexico (Guerrero state)",
        "adult_size": "5-6 inches",
        "growth_rate": "slow",
        "type": "terrestrial",
        "temperature_min": 72,
        "temperature_max": 82,
        "humidity_min": 60,
        "humidity_max": 70,
        "enclosure_size_sling": 'Small vial or 2x2x3"',
        "enclosure_size_juvenile": '5x5x5"',
        "enclosure_size_adult": '10x10x8" or 5-10 gallon tank',
        "substrate_depth": "3-4 inches",
        "substrate_type": "dry coco fiber or peat moss mix",
        "prey_size": "Appropriately sized prey (up to 2/3 body length)",
        "feeding_frequency_sling": "Every 4-5 days",
        "feeding_frequency_juvenile": "Once per week",
        "feeding_frequency_adult": "Every 1-2 weeks",
        "water_dish_required": True,
        "webbing_amount": "light",
        "burrowing": True,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Mexican Flame Knee** — Named for the vivid orange-flame knee markings that distinguish it from the similar *B. hamorii*. Also features orange on the carapace and abdomen. CITES Appendix II listed and rare in the wild. Hardy and beginner friendly. Keep dry with a small moist corner and always offer a water dish. Very slow grower. Docile but will flick urticating hairs if persistently stressed.",
        "is_verified": True,
    },
    {
        "scientific_name": "Brachypelma boehmei",
        "common_names": ["Mexican Fire Leg", "Mexican Rust Leg"],
        "genus": "Brachypelma",
        "family": "Theraphosidae",
        "care_level": CareLevel.INTERMEDIATE,
        "temperament": "defensive",
        "native_region": "Mexico (Guerrero, Oaxaca)",
        "adult_size": "5-6 inches",
        "growth_rate": "slow",
        "type": "terrestrial",
        "temperature_min": 72,
        "temperature_max": 82,
        "humidity_min": 60,
        "humidity_max": 70,
        "enclosure_size_sling": 'Small vial or 2x2x3"',
        "enclosure_size_juvenile": '5x5x5"',
        "enclosure_size_adult": '10x10x8" or 5-10 gallon tank',
        "substrate_depth": "3-4 inches",
        "substrate_type": "dry coco fiber or peat moss mix",
        "prey_size": "Appropriately sized prey (up to 2/3 body length)",
        "feeding_frequency_sling": "Every 4-5 days",
        "feeding_frequency_juvenile": "Once per week",
        "feeding_frequency_adult": "Every 1-2 weeks",
        "water_dish_required": True,
        "webbing_amount": "light",
        "burrowing": True,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Mexican Fire Leg** — Stunning species with vivid orange-red legs contrasting against a jet black body and carapace. More defensive than most other *Brachypelma* species — readily flicks urticating hairs and can be skittish. CITES Appendix II listed. Same husbandry as other Mexican *Brachypelma*: dry enclosure, moist corner, always-available water dish. Very slow grower. Not the best choice for beginners due to its defensive nature, but a manageable intermediate species.",
        "is_verified": True,
    },
    {
        "scientific_name": "Brachypelma klaasi",
        "common_names": ["Mexican Pink Tarantula", "Pink Tarantula"],
        "genus": "Brachypelma",
        "family": "Theraphosidae",
        "care_level": CareLevel.BEGINNER,
        "temperament": "docile",
        "native_region": "Mexico (Nayarit, Jalisco, Colima)",
        "adult_size": "5-6 inches",
        "growth_rate": "very slow",
        "type": "terrestrial",
        "temperature_min": 72,
        "temperature_max": 82,
        "humidity_min": 60,
        "humidity_max": 70,
        "enclosure_size_sling": 'Small vial or 2x2x3"',
        "enclosure_size_juvenile": '5x5x5"',
        "enclosure_size_adult": '10x10x8" or 5-10 gallon tank',
        "substrate_depth": "3-4 inches",
        "substrate_type": "dry coco fiber or peat moss mix",
        "prey_size": "Appropriately sized prey (up to 2/3 body length)",
        "feeding_frequency_sling": "Every 4-5 days",
        "feeding_frequency_juvenile": "Once per week",
        "feeding_frequency_adult": "Every 1-2 weeks",
        "water_dish_required": True,
        "webbing_amount": "light",
        "burrowing": True,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Mexican Pink Tarantula** — One of the rarest *Brachypelma* in the hobby. Characterized by pinkish/salmon coloration on the legs and carapace. CITES Appendix II listed with very small wild population range. Because of its rarity, captive-bred specimens are highly sought after. Husbandry is identical to other Mexican *Brachypelma*: dry enclosure, small moist corner, water dish always available. Extremely slow growth rate — one of the slowest in the genus. Docile and very similar in temperament to *B. hamorii*.",
        "is_verified": True,
    },
    {
        "scientific_name": "Eupalaestrus campestratus",
        "common_names": ["Pink Zebra Beauty", "PZB"],
        "genus": "Eupalaestrus",
        "family": "Theraphosidae",
        "care_level": CareLevel.BEGINNER,
        "temperament": "extremely docile",
        "native_region": "Paraguay, Argentina, Brazil",
        "adult_size": "5-6 inches",
        "growth_rate": "slow",
        "type": "terrestrial",
        "temperature_min": 68,
        "temperature_max": 78,
        "humidity_min": 65,
        "humidity_max": 75,
        "enclosure_size_sling": 'Small vial or 2x2x3"',
        "enclosure_size_juvenile": '5x5x5"',
        "enclosure_size_adult": '10x10x8" or 5-10 gallon tank',
        "substrate_depth": "3-4 inches",
        "substrate_type": "coco fiber, slightly moist",
        "prey_size": "Appropriately sized prey (up to 2/3 body length)",
        "feeding_frequency_sling": "Every 4-5 days",
        "feeding_frequency_juvenile": "Once per week",
        "feeding_frequency_adult": "Every 1-2 weeks",
        "water_dish_required": True,
        "webbing_amount": "light",
        "burrowing": True,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Pink Zebra Beauty** — Arguably one of the most docile tarantulas in the hobby. Named for the pink and black striped pattern on its legs. Comes from the grasslands and dry forests of South America. Tolerates slightly cooler temperatures than most tropical species — does well at room temperature in most homes. Slow grower but an incredibly rewarding and calm display animal. Rarely flicks hairs and almost never adopts a threat posture. An excellent beginner species.",
        "is_verified": True,
    },
    {
        "scientific_name": "Aphonopelma hentzi",
        "common_names": ["Texas Brown Tarantula", "Oklahoma Brown Tarantula"],
        "genus": "Aphonopelma",
        "family": "Theraphosidae",
        "care_level": CareLevel.BEGINNER,
        "temperament": "docile",
        "native_region": "Southern USA (Texas, Oklahoma, Kansas, New Mexico)",
        "adult_size": "3-4 inches",
        "growth_rate": "very slow",
        "type": "terrestrial",
        "temperature_min": 65,
        "temperature_max": 85,
        "humidity_min": 50,
        "humidity_max": 65,
        "enclosure_size_sling": 'Small vial or 2x2x2"',
        "enclosure_size_juvenile": '4x4x4"',
        "enclosure_size_adult": '8x8x6" or similar',
        "substrate_depth": "3-4 inches",
        "substrate_type": "dry coco fiber and sand mix (70/30)",
        "prey_size": "Appropriately sized prey (up to 2/3 body length)",
        "feeding_frequency_sling": "Every 5-7 days",
        "feeding_frequency_juvenile": "Once per week",
        "feeding_frequency_adult": "Every 2 weeks",
        "water_dish_required": True,
        "webbing_amount": "light",
        "burrowing": True,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Texas Brown Tarantula** — The most widespread native US tarantula. Males are commonly seen crossing roads in late summer and fall during breeding season, which is where most people first encounter this species. Females can live 35+ years in captivity, making this one of the longest-lived invertebrate pets available. Requires a dry enclosure with excellent ventilation. Very tolerant of temperature swings that match its native climate. A one-of-a-kind piece of American natural history.",
        "is_verified": True,
    },

    # ───────────────────────────────────────────────
    # NEW WORLD — INTERMEDIATE / ADVANCED TERRESTRIALS
    # ───────────────────────────────────────────────
    {
        "scientific_name": "Theraphosa blondi",
        "common_names": ["Goliath Birdeater", "Goliath Bird-Eating Spider"],
        "genus": "Theraphosa",
        "family": "Theraphosidae",
        "care_level": CareLevel.ADVANCED,
        "temperament": "defensive",
        "native_region": "Venezuela, Brazil, Guyana, Suriname",
        "adult_size": "10-11 inches",
        "growth_rate": "fast",
        "type": "terrestrial",
        "temperature_min": 75,
        "temperature_max": 82,
        "humidity_min": 80,
        "humidity_max": 90,
        "enclosure_size_sling": '2x2x3"',
        "enclosure_size_juvenile": '8x8x8"',
        "enclosure_size_adult": '18x18x12" or 20+ gallon tank',
        "substrate_depth": "6-8 inches",
        "substrate_type": "moist coco fiber and topsoil mix, deep and compactable",
        "prey_size": "Large prey — adult roaches, pinky mice, large crickets",
        "feeding_frequency_sling": "Every 3-4 days",
        "feeding_frequency_juvenile": "Once or twice per week",
        "feeding_frequency_adult": "Every 1-2 weeks",
        "water_dish_required": True,
        "webbing_amount": "moderate",
        "burrowing": True,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Goliath Birdeater** — The world's heaviest tarantula by mass and arguably the most impressive invertebrate in the hobby. Requires very high humidity (80–90%) and deep moist substrate. Possesses Type III urticating hairs — the most irritating kind — that can become airborne and cause significant skin and respiratory irritation. Stridulates (produces a hissing sound) as a warning. Large fangs capable of delivering a painful bite even if not medically significant. Requires large enclosure, frequent feeding, and experienced handling only. Not recommended for beginners. A stunning but demanding species.",
        "is_verified": True,
    },
    {
        "scientific_name": "Pamphobeteus antinous",
        "common_names": ["Bolivian Blue Leg Birdeater", "Steely Blue Leg Birdeater", "Bolivian Black Birdeater"],
        "genus": "Pamphobeteus",
        "family": "Theraphosidae",
        "care_level": CareLevel.INTERMEDIATE,
        "temperament": "shy, defensive when cornered",
        "native_region": "Bolivia, Peru",
        "adult_size": "8-9 inches",
        "growth_rate": "fast",
        "type": "terrestrial",
        "temperature_min": 75,
        "temperature_max": 85,
        "humidity_min": 60,
        "humidity_max": 75,
        "enclosure_size_sling": '2x2x3"',
        "enclosure_size_juvenile": '8x8x8"',
        "enclosure_size_adult": '15x15x10" or 15+ gallon tank',
        "substrate_depth": "5-6 inches",
        "substrate_type": "moist coco fiber and topsoil mix",
        "prey_size": "Large prey — adult roaches or large crickets",
        "feeding_frequency_sling": "Every 3-4 days",
        "feeding_frequency_juvenile": "Twice per week",
        "feeding_frequency_adult": "Once per week",
        "water_dish_required": True,
        "webbing_amount": "moderate",
        "burrowing": True,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Bolivian Blue Leg Birdeater** — Males display striking iridescent blue coloration on the legs and are among the most visually impressive tarantulas in the hobby. Females are larger but less colorful. More shy than aggressive — tends to retreat rather than threaten. A fossorial species that will burrow deeply given the opportunity. Common name varies in the trade ('Bolivian Black' typically refers to an undescribed cf. form). Fast growing with large appetites. A good step-up species from beginner-level tarantulas.",
        "is_verified": True,
    },
    {
        "scientific_name": "Nhandu tripepii",
        "common_names": ["Brazilian Giant Blonde"],
        "genus": "Nhandu",
        "family": "Theraphosidae",
        "care_level": CareLevel.INTERMEDIATE,
        "temperament": "defensive",
        "native_region": "Brazil",
        "adult_size": "7-8 inches",
        "growth_rate": "fast",
        "type": "terrestrial",
        "temperature_min": 75,
        "temperature_max": 82,
        "humidity_min": 70,
        "humidity_max": 80,
        "enclosure_size_sling": '2x2x3"',
        "enclosure_size_juvenile": '8x8x8"',
        "enclosure_size_adult": '12x12x10" or 15-gallon tank',
        "substrate_depth": "4-5 inches",
        "substrate_type": "moist coco fiber",
        "prey_size": "Large prey — adult roaches or large crickets",
        "feeding_frequency_sling": "Every 3-4 days",
        "feeding_frequency_juvenile": "Twice per week",
        "feeding_frequency_adult": "Once per week",
        "water_dish_required": True,
        "webbing_amount": "moderate",
        "burrowing": True,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Brazilian Giant Blonde** — A large, blonde-haired Brazilian species closely related to *N. chromatus*. Defensive and will readily flick urticating hairs. Faster growing than many similarly-sized species. Requires higher humidity than most terrestrial New World species. Not a handling species — flicks hairs aggressively when disturbed. An impressive display species for intermediate keepers comfortable with defensive tarantulas.",
        "is_verified": True,
    },
    {
        "scientific_name": "Megaphobema robustum",
        "common_names": ["Colombian Giant Redleg", "Colombian Giant"],
        "genus": "Megaphobema",
        "family": "Theraphosidae",
        "care_level": CareLevel.ADVANCED,
        "temperament": "defensive, fast",
        "native_region": "Colombia, Ecuador",
        "adult_size": "8-9 inches",
        "growth_rate": "medium",
        "type": "terrestrial",
        "temperature_min": 75,
        "temperature_max": 82,
        "humidity_min": 75,
        "humidity_max": 85,
        "enclosure_size_sling": '2x2x3"',
        "enclosure_size_juvenile": '8x8x8"',
        "enclosure_size_adult": '15x15x10" or 15+ gallon tank',
        "substrate_depth": "5-6 inches",
        "substrate_type": "moist coco fiber and topsoil",
        "prey_size": "Large prey — adult roaches or large crickets",
        "feeding_frequency_sling": "Every 3-4 days",
        "feeding_frequency_juvenile": "Twice per week",
        "feeding_frequency_adult": "Once per week",
        "water_dish_required": True,
        "webbing_amount": "moderate",
        "burrowing": True,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Colombian Giant Redleg** — A large, impressive species with vivid orange-red coloration on the leg joints. Can be extremely defensive and fast-moving — this species will spin rapidly to kick urticating hairs very effectively. Higher humidity requirements than most New World terrestrials. Requires a large enclosure with deep substrate. Advanced keepers only due to speed and defensive nature. Stunning display specimen when visible, though tends to be a fossorial species that spends significant time in its burrow.",
        "is_verified": True,
    },
    {
        "scientific_name": "Pterinopelma sazimai",
        "common_names": ["Brazilian Blue", "Sazima's Tarantula"],
        "genus": "Pterinopelma",
        "family": "Theraphosidae",
        "care_level": CareLevel.INTERMEDIATE,
        "temperament": "skittish",
        "native_region": "Brazil (Bahia state, Chapada Diamantina region)",
        "adult_size": "5-6 inches",
        "growth_rate": "medium",
        "type": "terrestrial",
        "temperature_min": 72,
        "temperature_max": 82,
        "humidity_min": 65,
        "humidity_max": 75,
        "enclosure_size_sling": 'Small vial or 2x2x3"',
        "enclosure_size_juvenile": '5x5x5"',
        "enclosure_size_adult": '10x10x8"',
        "substrate_depth": "3-4 inches",
        "substrate_type": "coco fiber, slightly moist",
        "prey_size": "Appropriately sized prey (up to 2/3 body length)",
        "feeding_frequency_sling": "Every 4-5 days",
        "feeding_frequency_juvenile": "Once per week",
        "feeding_frequency_adult": "Every 1-2 weeks",
        "water_dish_required": True,
        "webbing_amount": "moderate",
        "burrowing": True,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Brazilian Blue** — One of only a handful of truly blue New World tarantulas. Males display vivid iridescent blue coloration; females are less vibrant with brownish-blue tones. Native to the rocky tablelands (chapadas) of Bahia, Brazil. Skittish and fast-moving for a New World species but not overtly aggressive. Will burrow given sufficient substrate. A sought-after intermediate species due to its striking appearance. Comes from a region with distinct wet and dry seasons — allow the substrate to dry partially between mistings.",
        "is_verified": True,
    },

    # ───────────────────────────────────────────────
    # NEW WORLD — ARBOREAL
    # ───────────────────────────────────────────────
    {
        "scientific_name": "Avicularia purpurea",
        "common_names": ["Purple Pinktoe", "Ecuador Pinktoe"],
        "genus": "Avicularia",
        "family": "Theraphosidae",
        "care_level": CareLevel.INTERMEDIATE,
        "temperament": "docile, skittish",
        "native_region": "Ecuador",
        "adult_size": "4-5 inches",
        "growth_rate": "medium",
        "type": "arboreal",
        "temperature_min": 75,
        "temperature_max": 82,
        "humidity_min": 75,
        "humidity_max": 85,
        "enclosure_size_sling": 'Small arboreal vial, cross-ventilated',
        "enclosure_size_juvenile": '6x6x10" vertical',
        "enclosure_size_adult": '12x12x18" or taller vertical enclosure',
        "substrate_depth": "2-3 inches",
        "substrate_type": "coco fiber, kept slightly moist",
        "prey_size": "Appropriately sized prey (up to 2/3 body length)",
        "feeding_frequency_sling": "Every 3-4 days",
        "feeding_frequency_juvenile": "Twice per week",
        "feeding_frequency_adult": "Once per week",
        "water_dish_required": True,
        "webbing_amount": "heavy",
        "burrowing": False,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Purple Pinktoe** — A stunning arboreal species with deep purple-blue coloration on the body and vivid pink toes. Care is very similar to *A. avicularia* — requires a well-ventilated vertical enclosure with plenty of anchor points for webbing. Cross-ventilation (top and sides) is essential to prevent stagnant conditions that can be fatal. Does not flick urticating hairs but may spray defensive feces when threatened. Fast mover. Requires consistent high humidity but must not be kept in stagnant air. Provide a cork bark tube or artificial plant structure for webbing anchor.",
        "is_verified": True,
    },
    {
        "scientific_name": "Ybyrapora diversipes",
        "common_names": ["Amazon Sapphire Pinktoe", "Amazon Sapphire Pink-Toe"],
        "genus": "Ybyrapora",
        "family": "Theraphosidae",
        "care_level": CareLevel.INTERMEDIATE,
        "temperament": "docile, skittish",
        "native_region": "Brazil (Amazon basin)",
        "adult_size": "4-5 inches",
        "growth_rate": "medium",
        "type": "arboreal",
        "temperature_min": 72,
        "temperature_max": 80,
        "humidity_min": 65,
        "humidity_max": 75,
        "enclosure_size_sling": 'Small arboreal vial, cross-ventilated',
        "enclosure_size_juvenile": '6x6x10" vertical',
        "enclosure_size_adult": '12x12x18" or taller vertical enclosure',
        "substrate_depth": "2-3 inches",
        "substrate_type": "coco fiber, slightly moist",
        "prey_size": "Appropriately sized prey (up to 2/3 body length)",
        "feeding_frequency_sling": "Every 3-4 days",
        "feeding_frequency_juvenile": "Twice per week",
        "feeding_frequency_adult": "Once per week",
        "water_dish_required": True,
        "webbing_amount": "heavy",
        "burrowing": False,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Amazon Sapphire Pinktoe** — Jewel of the *Ybyrapora* genus. Slings display vivid blue coloration and dramatic red abdominal stripes that become more muted with each molt. Adults retain a stunning sapphire-blue sheen. Formerly classified as *Avicularia diversipes*. Requires slightly lower humidity than classic *Avicularia* species — good cross-ventilation is essential. Provide plenty of vertical space and cork bark for webbing. Fast mover and skittish but not aggressive. A highly sought-after display species.",
        "is_verified": True,
    },
    {
        "scientific_name": "Iridopelma hirsutum",
        "common_names": ["Bahia Scarlet", "Bahia Scarlet Birdeater"],
        "genus": "Iridopelma",
        "family": "Theraphosidae",
        "care_level": CareLevel.INTERMEDIATE,
        "temperament": "docile, skittish",
        "native_region": "Brazil (Bahia state)",
        "adult_size": "4-5 inches",
        "growth_rate": "medium",
        "type": "arboreal",
        "temperature_min": 75,
        "temperature_max": 82,
        "humidity_min": 75,
        "humidity_max": 85,
        "enclosure_size_sling": 'Small arboreal vial, cross-ventilated',
        "enclosure_size_juvenile": '6x6x10" vertical',
        "enclosure_size_adult": '12x12x18" vertical enclosure',
        "substrate_depth": "2-3 inches",
        "substrate_type": "coco fiber, slightly moist",
        "prey_size": "Appropriately sized prey (up to 2/3 body length)",
        "feeding_frequency_sling": "Every 3-4 days",
        "feeding_frequency_juvenile": "Twice per week",
        "feeding_frequency_adult": "Once per week",
        "water_dish_required": True,
        "webbing_amount": "heavy",
        "burrowing": False,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Bahia Scarlet** — A striking arboreal species endemic to Bahia state, Brazil. Slings display vivid scarlet-red coloration on the abdomen that fades with age to rich orange-brown tones. Related to *Avicularia* and requires similar cross-ventilated, vertical enclosure setup. Humidity should be high but air circulation is critical — stagnant humidity is fatal. Provide cork bark tubes or driftwood for webbing anchor points. A rarer species in the hobby, increasingly popular as captive breeding programs expand.",
        "is_verified": True,
    },

    # ───────────────────────────────────────────────
    # OLD WORLD AFRICA — TERRESTRIAL / FOSSORIAL
    # ───────────────────────────────────────────────
    {
        "scientific_name": "Harpactira pulchripes",
        "common_names": ["Golden Blue Leg Baboon", "Gold Blue Leg Baboon"],
        "genus": "Harpactira",
        "family": "Theraphosidae",
        "care_level": CareLevel.INTERMEDIATE,
        "temperament": "defensive, fast",
        "native_region": "South Africa (Eastern Cape, KwaZulu-Natal)",
        "adult_size": "4-5 inches",
        "growth_rate": "slow",
        "type": "terrestrial",
        "temperature_min": 68,
        "temperature_max": 75,
        "humidity_min": 50,
        "humidity_max": 65,
        "enclosure_size_sling": 'Small vial or 2x2x3"',
        "enclosure_size_juvenile": '5x5x5"',
        "enclosure_size_adult": '8x8x8" or similar',
        "substrate_depth": "4-6 inches",
        "substrate_type": "compact coco fiber and topsoil mix, slightly moist at depth",
        "prey_size": "Appropriately sized prey (up to 2/3 body length)",
        "feeding_frequency_sling": "Every 5-7 days",
        "feeding_frequency_juvenile": "Once per week",
        "feeding_frequency_adult": "Every 1-2 weeks",
        "water_dish_required": True,
        "webbing_amount": "moderate",
        "burrowing": True,
        "urticating_hairs": False,
        "medically_significant_venom": False,
        "care_guide": "**Golden Blue Leg Baboon** — One of the most visually stunning African baboon tarantulas. Adults display a golden-yellow carapace and abdomen with iridescent blue legs — a combination not seen in many other species. Comes from cooler, drier South African environments — keep temperatures lower than most tropical species (68–75°F is ideal). Old World species with no urticating hairs; defensive if disturbed. Fossorial — provide compactable substrate at least 4 inches deep. Slow grower. No medically significant venom reported. A truly rewarding intermediate species.",
        "is_verified": True,
    },
    {
        "scientific_name": "Pelinobius muticus",
        "common_names": ["King Baboon Tarantula", "King Baboon"],
        "genus": "Pelinobius",
        "family": "Theraphosidae",
        "care_level": CareLevel.ADVANCED,
        "temperament": "extremely defensive",
        "native_region": "Kenya, Tanzania",
        "adult_size": "8-9 inches",
        "growth_rate": "slow",
        "type": "fossorial",
        "temperature_min": 75,
        "temperature_max": 84,
        "humidity_min": 60,
        "humidity_max": 70,
        "enclosure_size_sling": 'Small vial or 2x2x3"',
        "enclosure_size_juvenile": '6x6x6"',
        "enclosure_size_adult": '15x15x12" or 20-gallon tank',
        "substrate_depth": "8-10 inches",
        "substrate_type": "dry coco fiber and topsoil mix, compactable",
        "prey_size": "Large prey — adult roaches or large crickets",
        "feeding_frequency_sling": "Every 5-7 days",
        "feeding_frequency_juvenile": "Once per week",
        "feeding_frequency_adult": "Every 2 weeks",
        "water_dish_required": True,
        "webbing_amount": "moderate",
        "burrowing": True,
        "urticating_hairs": False,
        "medically_significant_venom": False,
        "care_guide": "**King Baboon** — One of the largest and most formidable African tarantulas. An obligate burrower that will construct elaborate tunnel systems given deep enough substrate (8–10 inches minimum). Extremely defensive — will rear up, stridulate (producing a loud hissing sound by rubbing its legs), and bite without hesitation. Large fangs that can deliver a very painful bite even if not medically significant. Keep dry — comes from the semi-arid scrublands of East Africa. Slow grower but very long-lived. The stridulation sound alone makes this an impressive display animal. Experts only.",
        "is_verified": True,
    },
    {
        "scientific_name": "Ceratogyrus marshalli",
        "common_names": ["Straight Horned Baboon", "Marshall's Horned Baboon"],
        "genus": "Ceratogyrus",
        "family": "Theraphosidae",
        "care_level": CareLevel.INTERMEDIATE,
        "temperament": "defensive",
        "native_region": "Zimbabwe, Mozambique, South Africa",
        "adult_size": "4-5 inches",
        "growth_rate": "medium",
        "type": "fossorial",
        "temperature_min": 75,
        "temperature_max": 85,
        "humidity_min": 60,
        "humidity_max": 70,
        "enclosure_size_sling": 'Small vial or 2x2x3"',
        "enclosure_size_juvenile": '5x5x5"',
        "enclosure_size_adult": '10x10x8"',
        "substrate_depth": "4-6 inches",
        "substrate_type": "dry to slightly moist coco fiber, compactable",
        "prey_size": "Appropriately sized prey (up to 2/3 body length)",
        "feeding_frequency_sling": "Every 4-5 days",
        "feeding_frequency_juvenile": "Once per week",
        "feeding_frequency_adult": "Every 1-2 weeks",
        "water_dish_required": False,
        "webbing_amount": "heavy",
        "burrowing": True,
        "urticating_hairs": False,
        "medically_significant_venom": False,
        "care_guide": "**Straight Horned Baboon** — Like its relative *C. darlingi*, this species has a foveal horn on its carapace — the function of which is still debated in the scientific community. The 'Straight' in its common name refers to the horn being more upright compared to *C. darlingi*'s curved horn. An obligate burrower from drier southern African regions. Defensive but slightly less reactive than *C. darlingi*. Provide a water overflow near the entrance to the burrow rather than a standing dish — wet substrate at depth keeps the animal hydrated naturally. Heavy webber.",
        "is_verified": True,
    },
    {
        "scientific_name": "Hysterocrates gigas",
        "common_names": ["Cameroon Red Baboon", "Cameroon Red"],
        "genus": "Hysterocrates",
        "family": "Theraphosidae",
        "care_level": CareLevel.INTERMEDIATE,
        "temperament": "defensive but not overtly aggressive",
        "native_region": "Cameroon, Nigeria (West/Central Africa)",
        "adult_size": "6-7 inches",
        "growth_rate": "fast",
        "type": "fossorial",
        "temperature_min": 75,
        "temperature_max": 82,
        "humidity_min": 75,
        "humidity_max": 85,
        "enclosure_size_sling": 'Small vial or 2x2x3"',
        "enclosure_size_juvenile": '6x6x6"',
        "enclosure_size_adult": '12x12x10" or 10-gallon tank',
        "substrate_depth": "6-8 inches",
        "substrate_type": "moist coco fiber and topsoil, heavily moistened — needs to maintain tunnels",
        "prey_size": "Large prey — adult roaches or large crickets",
        "feeding_frequency_sling": "Every 3-4 days",
        "feeding_frequency_juvenile": "Twice per week",
        "feeding_frequency_adult": "Once per week",
        "water_dish_required": True,
        "webbing_amount": "moderate",
        "burrowing": True,
        "urticating_hairs": False,
        "medically_significant_venom": False,
        "care_guide": "**Cameroon Red Baboon** — A large, impressive fossorial African species known for its rich reddish-brown coloration and fast growth rate. An obligate burrower requiring deep, moist substrate that can hold tunnel structure. Often associated with water sources in the wild — a water dish is important and some keepers incorporate small water features. Research (Shillington 2002) found that juvenile groups show unusually high mutual tolerance and cooperative feeding behavior; keeper experiences with communal setups are genuinely mixed, with success most commonly reported during the juvenile stage. The main communal risk is during molts, when tankmates may prey on a vulnerable individual. No urticating hairs. Defensive but not highly aggressive unprovoked. Old World species — do not handle.",
        "is_verified": True,
    },

    # ───────────────────────────────────────────────
    # OLD WORLD AFRICA — ARBOREAL
    # ───────────────────────────────────────────────
    {
        "scientific_name": "Heteroscodra maculata",
        "common_names": ["Togo Starburst Baboon", "Ornamental Baboon"],
        "genus": "Heteroscodra",
        "family": "Theraphosidae",
        "care_level": CareLevel.ADVANCED,
        "temperament": "extremely defensive, fast",
        "native_region": "West Africa (Togo, Ghana, Nigeria)",
        "adult_size": "5-6 inches",
        "growth_rate": "fast",
        "type": "arboreal",
        "temperature_min": 75,
        "temperature_max": 84,
        "humidity_min": 65,
        "humidity_max": 75,
        "enclosure_size_sling": 'Small arboreal vial, cross-ventilated',
        "enclosure_size_juvenile": '6x6x10" vertical',
        "enclosure_size_adult": '12x12x18" tall vertical enclosure',
        "substrate_depth": "2-3 inches",
        "substrate_type": "dry to slightly moist coco fiber",
        "prey_size": "Appropriately sized prey (up to 2/3 body length)",
        "feeding_frequency_sling": "Every 3-4 days",
        "feeding_frequency_juvenile": "Twice per week",
        "feeding_frequency_adult": "Once per week",
        "water_dish_required": True,
        "webbing_amount": "heavy",
        "burrowing": False,
        "urticating_hairs": False,
        "medically_significant_venom": False,
        "care_guide": "**Togo Starburst Baboon** — A beautiful but extremely defensive West African arboreal species with a distinctive starburst pattern on the carapace. Old World arboreal with no urticating hairs and no medically significant venom recorded, but will bite readily and is extremely fast. Not a beginner or even intermediate species — the combination of speed, defensiveness, and arboreal habit makes husbandry operations (rehousing, cleaning) genuinely risky. Requires a tall, cross-ventilated enclosure with cork bark for anchoring webbing. Keepers should have a solid containment protocol before acquiring this species.",
        "is_verified": True,
    },
    {
        "scientific_name": "Stromatopelma calceatum",
        "common_names": ["Featherleg Baboon", "Feather Leg Baboon Tarantula"],
        "genus": "Stromatopelma",
        "family": "Theraphosidae",
        "care_level": CareLevel.ADVANCED,
        "temperament": "extremely defensive, very fast",
        "native_region": "West Africa (Sierra Leone, Ghana, Nigeria, Cameroon)",
        "adult_size": "5-6 inches",
        "growth_rate": "fast",
        "type": "arboreal",
        "temperature_min": 75,
        "temperature_max": 85,
        "humidity_min": 65,
        "humidity_max": 75,
        "enclosure_size_sling": 'Small arboreal vial, cross-ventilated',
        "enclosure_size_juvenile": '6x6x10" vertical',
        "enclosure_size_adult": '12x12x18" tall vertical enclosure',
        "substrate_depth": "2-3 inches",
        "substrate_type": "dry to slightly moist coco fiber",
        "prey_size": "Appropriately sized prey (up to 2/3 body length)",
        "feeding_frequency_sling": "Every 3-4 days",
        "feeding_frequency_juvenile": "Twice per week",
        "feeding_frequency_adult": "Once per week",
        "water_dish_required": True,
        "webbing_amount": "heavy",
        "burrowing": False,
        "urticating_hairs": False,
        "medically_significant_venom": False,
        "care_guide": "**Featherleg Baboon** — Named for the distinctive feathery setae visible on the legs. Widely considered one of the most defensive tarantulas in the hobby — will strike repeatedly with almost no provocation and is extremely fast. Old World species with no urticating hairs; bites have been described as painful with localized effects. Requires a tall, well-ventilated arboreal enclosure. Maintenance operations (refilling water dishes, spot cleaning) carry significant bite risk and should be approached with great care. Experts only. An impressive display species when visible, but visibility is often limited as it tends to stay deep in its webbing.",
        "is_verified": True,
    },

    # ───────────────────────────────────────────────
    # OLD WORLD ASIA — POECILOTHERIA
    # ───────────────────────────────────────────────
    {
        "scientific_name": "Poecilotheria ornata",
        "common_names": ["Fringed Ornamental", "Ornate Parachute Spider"],
        "genus": "Poecilotheria",
        "family": "Theraphosidae",
        "care_level": CareLevel.ADVANCED,
        "temperament": "defensive, fast",
        "native_region": "Sri Lanka (endemic)",
        "adult_size": "8-9 inches",
        "growth_rate": "fast",
        "type": "arboreal",
        "temperature_min": 75,
        "temperature_max": 85,
        "humidity_min": 70,
        "humidity_max": 80,
        "enclosure_size_sling": 'Small arboreal vial, cross-ventilated',
        "enclosure_size_juvenile": '8x8x12" vertical',
        "enclosure_size_adult": '18x18x24" tall vertical enclosure',
        "substrate_depth": "2-3 inches",
        "substrate_type": "coco fiber, slightly moist",
        "prey_size": "Large prey — adult roaches, large crickets",
        "feeding_frequency_sling": "Every 3-4 days",
        "feeding_frequency_juvenile": "Twice per week",
        "feeding_frequency_adult": "Once per week",
        "water_dish_required": True,
        "webbing_amount": "heavy",
        "burrowing": False,
        "urticating_hairs": False,
        "medically_significant_venom": True,
        "care_guide": "**Fringed Ornamental** — The largest *Poecilotheria* species, with a leg span that can exceed 8 inches. Stunning geometric patterning on the abdomen and yellow/black coloration on the underside. **MEDICALLY SIGNIFICANT VENOM** — bites have caused intense muscle cramping, prolonged pain, and in some cases required hospitalization. Extremely fast and defensive. IUCN listed as Critically Endangered in the wild. All *Poecilotheria* require experienced keepers with solid containment protocols. Requires tall vertical enclosure with cork bark slabs and good cross-ventilation. Never handle. Experts only.",
        "is_verified": True,
    },
    {
        "scientific_name": "Poecilotheria fasciata",
        "common_names": ["Sri Lankan Ornamental", "Fringed Parachute Spider"],
        "genus": "Poecilotheria",
        "family": "Theraphosidae",
        "care_level": CareLevel.ADVANCED,
        "temperament": "defensive, fast",
        "native_region": "Sri Lanka (endemic)",
        "adult_size": "6-7 inches",
        "growth_rate": "fast",
        "type": "arboreal",
        "temperature_min": 75,
        "temperature_max": 85,
        "humidity_min": 70,
        "humidity_max": 80,
        "enclosure_size_sling": 'Small arboreal vial, cross-ventilated',
        "enclosure_size_juvenile": '8x8x12" vertical',
        "enclosure_size_adult": '14x14x18" tall vertical enclosure',
        "substrate_depth": "2-3 inches",
        "substrate_type": "coco fiber, slightly moist",
        "prey_size": "Appropriately sized prey (up to 2/3 body length)",
        "feeding_frequency_sling": "Every 3-4 days",
        "feeding_frequency_juvenile": "Twice per week",
        "feeding_frequency_adult": "Once per week",
        "water_dish_required": True,
        "webbing_amount": "heavy",
        "burrowing": False,
        "urticating_hairs": False,
        "medically_significant_venom": True,
        "care_guide": "**Sri Lankan Ornamental** — One of the original *Poecilotheria* species in the hobby. Features bold brown and cream banding on the legs with a striking yellow and black underside. **MEDICALLY SIGNIFICANT VENOM** — same risk profile as all *Poecilotheria*: bites cause intense localized pain, muscle cramps, and systemic effects in some individuals. Fast, defensive, and capable of moving across an enclosure faster than most keepers expect. IUCN Vulnerable. Requires tall vertical enclosure with good ventilation and hiding spots. Only for experienced keepers with established containment protocols.",
        "is_verified": True,
    },
    {
        "scientific_name": "Poecilotheria subfusca",
        "common_names": ["Ivory Ornamental", "Highland Ornamental"],
        "genus": "Poecilotheria",
        "family": "Theraphosidae",
        "care_level": CareLevel.ADVANCED,
        "temperament": "defensive, fast",
        "native_region": "Sri Lanka (endemic, highland montane forests)",
        "adult_size": "6-7 inches",
        "growth_rate": "medium",
        "type": "arboreal",
        "temperature_min": 72,
        "temperature_max": 80,
        "humidity_min": 70,
        "humidity_max": 80,
        "enclosure_size_sling": 'Small arboreal vial, cross-ventilated',
        "enclosure_size_juvenile": '8x8x12" vertical',
        "enclosure_size_adult": '14x14x18" tall vertical enclosure',
        "substrate_depth": "2-3 inches",
        "substrate_type": "coco fiber, slightly moist",
        "prey_size": "Appropriately sized prey (up to 2/3 body length)",
        "feeding_frequency_sling": "Every 3-4 days",
        "feeding_frequency_juvenile": "Twice per week",
        "feeding_frequency_adult": "Once per week",
        "water_dish_required": True,
        "webbing_amount": "heavy",
        "burrowing": False,
        "urticating_hairs": False,
        "medically_significant_venom": True,
        "care_guide": "**Ivory Ornamental** — The most distinctive *Poecilotheria* in terms of coloration — adults develop a beautiful ivory/cream-grey pattern that makes them one of the most visually unique ornamentals. Native to cooler highland montane forests of Sri Lanka and tolerates slightly lower temperatures than other *Poecilotheria* (72–80°F). **MEDICALLY SIGNIFICANT VENOM** — same cautions apply as all genus members. Slightly slower growing than other *Poecilotheria*. IUCN Critically Endangered. Captive breeding is important for the long-term availability of this species. Experts only.",
        "is_verified": True,
    },

    # ───────────────────────────────────────────────
    # OLD WORLD ASIA — OTHER
    # ───────────────────────────────────────────────
    {
        "scientific_name": "Cyriopagopus lividus",
        "common_names": ["Cobalt Blue Tarantula"],
        "genus": "Cyriopagopus",
        "family": "Theraphosidae",
        "care_level": CareLevel.ADVANCED,
        "temperament": "extremely defensive, very fast",
        "native_region": "Myanmar, Thailand, Laos, Cambodia, Vietnam",
        "adult_size": "4-5 inches",
        "growth_rate": "medium",
        "type": "fossorial",
        "temperature_min": 77,
        "temperature_max": 85,
        "humidity_min": 75,
        "humidity_max": 85,
        "enclosure_size_sling": 'Small vial or 2x2x3"',
        "enclosure_size_juvenile": '5x5x5"',
        "enclosure_size_adult": '10x10x8"',
        "substrate_depth": "6-8 inches",
        "substrate_type": "moist coco fiber and topsoil, compactable for deep burrows",
        "prey_size": "Appropriately sized prey (up to 2/3 body length)",
        "feeding_frequency_sling": "Every 4-5 days",
        "feeding_frequency_juvenile": "Once per week",
        "feeding_frequency_adult": "Every 1-2 weeks",
        "water_dish_required": True,
        "webbing_amount": "heavy",
        "burrowing": True,
        "urticating_hairs": False,
        "medically_significant_venom": True,
        "care_guide": "**Cobalt Blue Tarantula** — One of the most visually striking tarantulas in the world — iridescent cobalt blue coloration that must be seen in person to be fully appreciated. Formerly known as *Haplopelma lividum*. An obligate burrower that spends most of its life underground; rarely seen except at feeding time. **MEDICALLY SIGNIFICANT VENOM** — documented bite reports describe severe muscle cramps and intense pain (PubMed case reports confirm this). Combined with its speed and extreme defensiveness, this is a serious advanced-only species. High humidity and deep moist substrate are essential. Maintenance operations carry significant bite risk — use a catch cup and take no shortcuts.",
        "is_verified": True,
    },
    {
        "scientific_name": "Chilobrachys fimbriatus",
        "common_names": ["Indian Violet", "Indian Violet Tarantula"],
        "genus": "Chilobrachys",
        "family": "Theraphosidae",
        "care_level": CareLevel.INTERMEDIATE,
        "temperament": "defensive, fast",
        "native_region": "India (Maharashtra, Karnataka, Kerala)",
        "adult_size": "5-6 inches",
        "growth_rate": "fast",
        "type": "fossorial",
        "temperature_min": 75,
        "temperature_max": 82,
        "humidity_min": 60,
        "humidity_max": 70,
        "enclosure_size_sling": 'Small vial or 2x2x3"',
        "enclosure_size_juvenile": '5x5x5"',
        "enclosure_size_adult": '10x10x8"',
        "substrate_depth": "5-6 inches",
        "substrate_type": "moist coco fiber and topsoil, compactable for burrowing",
        "prey_size": "Appropriately sized prey (up to 2/3 body length)",
        "feeding_frequency_sling": "Every 4-5 days",
        "feeding_frequency_juvenile": "Once per week",
        "feeding_frequency_adult": "Every 1-2 weeks",
        "water_dish_required": True,
        "webbing_amount": "heavy",
        "burrowing": True,
        "urticating_hairs": False,
        "medically_significant_venom": False,
        "care_guide": "**Indian Violet** — A beautiful fossorial Old World species from the tropical forests of western India. Adults develop a subtle violet-purple iridescence on the legs that is particularly visible under natural light — hence the common name. An obligate burrower that constructs deep, silk-lined tunnels and covers the entrance with a heavy webbing 'door'. Defensive and fast but generally less reactive than many other Old World fossorials. Heavy webber — the enclosure entrance will often be completely covered in silk. Keep moderately moist with dry spells between mistings to replicate the seasonal monsoon climate. Fast growing and a reliable feeder.",
        "is_verified": True,
    },
]


def seed():
    """Seed batch 2 — adds 25 species to reach 50 total."""
    print("Connecting to database...")
    db = SessionLocal()

    try:
        count = db.query(Species).count()
        print(f"Current species count: {count}")

        added = 0
        skipped = 0

        for data in SPECIES_DATA:
            existing = db.query(Species).filter(
                Species.scientific_name_lower == data["scientific_name"].lower()
            ).first()

            if existing:
                skipped += 1
                print(f"  Skipped (exists): {data['scientific_name']}")
                continue

            species = Species(
                id=uuid.uuid4(),
                scientific_name_lower=data["scientific_name"].lower(),
                **data,
            )
            db.add(species)
            added += 1
            print(f"  Added: {data['scientific_name']}")

        db.commit()
        print(f"\nDone! Added {added}, skipped {skipped} (already existed).")
        print(f"New total: {db.query(Species).count()} species")

    except Exception as e:
        print(f"Error: {e}")
        db.rollback()
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed()
