"""
Seed popular tarantula species with comprehensive care data

Run with: python3 seed_species.py
"""

import sys
import os
import uuid

# Add the app directory to the Python path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from app.database import SessionLocal
from app.models.species import Species, CareLevel


SPECIES_DATA = [
    {
        "scientific_name": "Grammostola rosea",
        "common_names": ["Chilean Rose Hair", "Rose Hair Tarantula"],
        "genus": "Grammostola",
        "family": "Theraphosidae",
        "care_level": CareLevel.BEGINNER,
        "temperament": "docile",
        "native_region": "Chile, Bolivia, Argentina",
        "adult_size": "5-6 inches",
        "growth_rate": "slow",
        "type": "terrestrial",
        "temperature_min": 65,
        "temperature_max": 80,
        "humidity_min": 60,
        "humidity_max": 70,
        "enclosure_size_sling": 'Small vial or 2x2x3"',
        "enclosure_size_juvenile": '5x5x5" or similar',
        "enclosure_size_adult": '10x10x10" or 5-10 gallon tank',
        "substrate_depth": "3-4 inches",
        "substrate_type": "coco fiber, peat moss, or potting soil",
        "prey_size": "Appropriately sized prey (1/2 to 2/3 body length)",
        "feeding_frequency_sling": "Every 2-3 days",
        "feeding_frequency_juvenile": "Twice per week",
        "feeding_frequency_adult": "Once per week",
        "water_dish_required": True,
        "webbing_amount": "moderate",
        "burrowing": False,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Chilean Rose Hair** - One of the most popular pet tarantulas. Very hardy and forgiving of beginner mistakes. Can go months without eating (not uncommon). Very slow growth rate means slings take years to reach adult size. Generally docile but can be unpredictable.",
        "is_verified": True,
    },
    {
        "scientific_name": "Brachypelma hamorii",
        "common_names": ["Mexican Red Knee", "Mexican Redknee Tarantula"],
        "genus": "Brachypelma",
        "family": "Theraphosidae",
        "care_level": CareLevel.BEGINNER,
        "temperament": "docile",
        "native_region": "Mexico",
        "adult_size": "5-6 inches",
        "growth_rate": "slow",
        "type": "terrestrial",
        "temperature_min": 70,
        "temperature_max": 85,
        "humidity_min": 60,
        "humidity_max": 70,
        "enclosure_size_adult": '10x10x10" or 5-10 gallon tank',
        "substrate_depth": "3-4 inches",
        "substrate_type": "coco fiber or peat moss",
        "prey_size": "Appropriately sized crickets, roaches, or mealworms",
        "feeding_frequency_adult": "Once per week",
        "water_dish_required": True,
        "webbing_amount": "light",
        "burrowing": True,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Mexican Red Knee** - Iconic species with beautiful red/orange markings. Very docile and easy to care for. Slow growing but worth the wait. Great display species. Threatened in the wild, most in the hobby are captive bred.",
        "is_verified": True,
    },
    {
        "scientific_name": "Aphonopelma chalcodes",
        "common_names": ["Desert Blonde", "Arizona Blonde"],
        "genus": "Aphonopelma",
        "family": "Theraphosidae",
        "care_level": CareLevel.BEGINNER,
        "temperament": "docile",
        "native_region": "Southwestern United States, Mexico",
        "adult_size": "5-6 inches",
        "growth_rate": "slow",
        "type": "terrestrial",
        "temperature_min": 70,
        "temperature_max": 85,
        "humidity_min": 50,
        "humidity_max": 65,
        "substrate_depth": "3-4 inches",
        "substrate_type": "dry coco fiber or sand mix",
        "water_dish_required": True,
        "webbing_amount": "light",
        "burrowing": True,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Desert Blonde** - Hardy desert species. Tolerates dry conditions well. Very docile and rarely flicks hairs. Slow growing but very low maintenance.",
        "is_verified": True,
    },
    {
        "scientific_name": "Caribena versicolor",
        "common_names": ["Antilles Pinktoe", "Martinique Pinktoe"],
        "genus": "Caribena",
        "family": "Theraphosidae",
        "care_level": CareLevel.BEGINNER,
        "temperament": "docile, skittish",
        "native_region": "Martinique, Guadeloupe",
        "adult_size": "5-6 inches",
        "growth_rate": "fast",
        "type": "arboreal",
        "temperature_min": 75,
        "temperature_max": 85,
        "humidity_min": 75,
        "humidity_max": 85,
        "enclosure_size_adult": '12x12x18" or similar vertical enclosure',
        "substrate_depth": "2-3 inches",
        "substrate_type": "coco fiber",
        "prey_size": "Appropriately sized flying insects preferred",
        "feeding_frequency_sling": "Every 2-3 days",
        "feeding_frequency_adult": "Once or twice per week",
        "water_dish_required": True,
        "webbing_amount": "heavy",
        "burrowing": False,
        "urticating_hairs": False,
        "medically_significant_venom": False,
        "care_guide": "**Antilles Pinktoe** - Beautiful color changes from blue sling to pink/purple adult. Arboreal species that creates impressive webbing. Fast growing. Skittish but not aggressive. Requires higher humidity.",
        "is_verified": True,
    },
    {
        "scientific_name": "Tliltocatl albopilosus",
        "common_names": ["Curly Hair Tarantula", "Honduran Curly Hair"],
        "genus": "Tliltocatl",
        "family": "Theraphosidae",
        "care_level": CareLevel.BEGINNER,
        "temperament": "docile",
        "native_region": "Central America",
        "adult_size": "5-6 inches",
        "growth_rate": "medium",
        "type": "terrestrial",
        "temperature_min": 70,
        "temperature_max": 80,
        "humidity_min": 65,
        "humidity_max": 75,
        "substrate_depth": "3-4 inches",
        "substrate_type": "coco fiber",
        "water_dish_required": True,
        "webbing_amount": "moderate",
        "burrowing": True,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Curly Hair** - Named for distinctive curly setae. Very hardy and forgiving species. Good eater with medium growth rate. Great beginner tarantula.",
        "is_verified": True,
    },
    {
        "scientific_name": "Grammostola pulchra",
        "common_names": ["Brazilian Black"],
        "genus": "Grammostola",
        "family": "Theraphosidae",
        "care_level": CareLevel.BEGINNER,
        "temperament": "docile",
        "native_region": "Brazil",
        "adult_size": "4-5 inches",
        "growth_rate": "slow",
        "type": "terrestrial",
        "temperature_min": 72,
        "temperature_max": 79,
        "humidity_min": 65,
        "humidity_max": 75,
        "substrate_depth": "3-4 inches",
        "substrate_type": "coco fiber",
        "water_dish_required": True,
        "webbing_amount": "light",
        "burrowing": False,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Brazilian Black** - Glossy black coloration. Extremely docile and one of the best pet species. Slow growing but incredibly beginner-friendly. Excellent temperament.",
        "is_verified": True,
    },
    {
        "scientific_name": "Avicularia avicularia",
        "common_names": ["Pink Toe Tarantula"],
        "genus": "Avicularia",
        "family": "Theraphosidae",
        "care_level": CareLevel.INTERMEDIATE,
        "temperament": "docile",
        "native_region": "South America",
        "adult_size": "5-6 inches",
        "growth_rate": "medium",
        "type": "arboreal",
        "temperature_min": 75,
        "temperature_max": 82,
        "humidity_min": 75,
        "humidity_max": 85,
        "enclosure_size_adult": '8x8x12" or similar vertical enclosure',
        "substrate_depth": "2-3 inches",
        "substrate_type": "coco fiber",
        "water_dish_required": True,
        "webbing_amount": "heavy",
        "burrowing": False,
        "urticating_hairs": False,
        "medically_significant_venom": False,
        "care_guide": "**Pink Toe Tarantula** - Classic arboreal species with distinctive pink feet. Skittish but not aggressive. Fast grower. Requires high humidity and vertical space.",
        "is_verified": True,
    },
    {
        "scientific_name": "Chromatopelma cyaneopubescens",
        "common_names": ["Green Bottle Blue", "GBB"],
        "genus": "Chromatopelma",
        "family": "Theraphosidae",
        "care_level": CareLevel.INTERMEDIATE,
        "temperament": "skittish",
        "native_region": "Venezuela",
        "adult_size": "5-6 inches",
        "growth_rate": "fast",
        "type": "terrestrial",
        "temperature_min": 75,
        "temperature_max": 82,
        "humidity_min": 65,
        "humidity_max": 75,
        "substrate_depth": "3-4 inches",
        "substrate_type": "dry coco fiber",
        "water_dish_required": True,
        "webbing_amount": "heavy",
        "burrowing": False,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Green Bottle Blue** - Stunning iridescent blue coloration. Fast grower and good feeder. Can be defensive and webbing is excessive. Not for handling.",
        "is_verified": True,
    },
    {
        "scientific_name": "Lasiodora parahybana",
        "common_names": ["Brazilian Salmon Pink", "LP"],
        "genus": "Lasiodora",
        "family": "Theraphosidae",
        "care_level": CareLevel.INTERMEDIATE,
        "temperament": "calm",
        "native_region": "Brazil",
        "adult_size": "9-10 inches",
        "growth_rate": "very fast",
        "type": "terrestrial",
        "temperature_min": 75,
        "temperature_max": 82,
        "humidity_min": 70,
        "humidity_max": 80,
        "substrate_depth": "4-5 inches",
        "substrate_type": "coco fiber",
        "water_dish_required": True,
        "webbing_amount": "moderate",
        "burrowing": True,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Brazilian Salmon Pink** - One of the largest and fastest growing species. Requires large enclosure. Heavy eater. Can be defensive but generally calm. Impressive display species.",
        "is_verified": True,
    },
    {
        "scientific_name": "Nhandu chromatus",
        "common_names": ["Brazilian Red and White"],
        "genus": "Nhandu",
        "family": "Theraphosidae",
        "care_level": CareLevel.INTERMEDIATE,
        "temperament": "defensive",
        "native_region": "Brazil",
        "adult_size": "7-8 inches",
        "growth_rate": "fast",
        "type": "terrestrial",
        "temperature_min": 75,
        "temperature_max": 82,
        "humidity_min": 70,
        "humidity_max": 80,
        "substrate_depth": "4-5 inches",
        "substrate_type": "coco fiber",
        "water_dish_required": True,
        "webbing_amount": "moderate",
        "burrowing": True,
        "urticating_hairs": True,
        "medically_significant_venom": False,
        "care_guide": "**Brazilian Red and White** - Large and impressive species with striking red and white markings. Fast growing and defensive. Readily flicks hairs. Not for beginners.",
        "is_verified": True,
    },
    {
        "scientific_name": "Poecilotheria metallica",
        "common_names": ["Gooty Sapphire", "Peacock Parachute Spider"],
        "genus": "Poecilotheria",
        "family": "Theraphosidae",
        "care_level": CareLevel.ADVANCED,
        "temperament": "defensive",
        "native_region": "India",
        "adult_size": "6-7 inches",
        "growth_rate": "fast",
        "type": "arboreal",
        "temperature_min": 75,
        "temperature_max": 82,
        "humidity_min": 75,
        "humidity_max": 85,
        "enclosure_size_adult": '12x12x18" tall or similar vertical enclosure',
        "substrate_depth": "2-3 inches",
        "substrate_type": "coco fiber",
        "water_dish_required": True,
        "webbing_amount": "heavy",
        "burrowing": False,
        "urticating_hairs": False,
        "medically_significant_venom": True,
        "care_guide": "**Gooty Sapphire Ornamental** - Stunningly beautiful with metallic blue coloration. DANGEROUS - Medically significant venom and extremely fast/defensive. Experts only.",
        "is_verified": True,
    },
    {
        "scientific_name": "Pterinochilus murinus",
        "common_names": ["Orange Baboon Tarantula", "OBT"],
        "genus": "Pterinochilus",
        "family": "Theraphosidae",
        "care_level": CareLevel.ADVANCED,
        "temperament": "aggressive",
        "native_region": "Africa",
        "adult_size": "5-6 inches",
        "growth_rate": "fast",
        "type": "terrestrial",
        "temperature_min": 75,
        "temperature_max": 82,
        "humidity_min": 60,
        "humidity_max": 70,
        "substrate_depth": "6-8 inches",
        "substrate_type": "dry coco fiber",
        "water_dish_required": False,
        "webbing_amount": "heavy",
        "burrowing": True,
        "urticating_hairs": False,
        "medically_significant_venom": False,
        "care_guide": "**Orange Baboon Tarantula** - HIGHLY AGGRESSIVE and will bite without provocation. Very fast. Only for experts with containment experience. Not a pet for display.",
        "is_verified": True,
    },
    {
        "scientific_name": "Heteroscodra maculata",
        "common_names": ["Togo Starburst", "Ornamental Baboon"],
        "genus": "Heteroscodra",
        "family": "Theraphosidae",
        "care_level": CareLevel.ADVANCED,
        "temperament": "defensive",
        "native_region": "Africa",
        "adult_size": "5-6 inches",
        "growth_rate": "fast",
        "type": "arboreal",
        "temperature_min": 75,
        "temperature_max": 82,
        "humidity_min": 75,
        "humidity_max": 85,
        "enclosure_size_adult": '12x12x18" tall or similar vertical enclosure',
        "substrate_depth": "2-3 inches",
        "substrate_type": "coco fiber",
        "water_dish_required": True,
        "webbing_amount": "heavy",
        "burrowing": False,
        "urticating_hairs": False,
        "medically_significant_venom": False,
        "care_guide": "**Togo Starburst** - Beautifully patterned arboreal species with striking colors. Fast and defensive. Will bite readily. Experts only.",
        "is_verified": True,
    },
]


def seed():
    """Seed the database with common tarantula species."""
    print("Connecting to database...")
    db = SessionLocal()

    try:
        count = db.query(Species).count()
        print(f"Current species count: {count}")

        added = 0
        skipped = 0

        for data in SPECIES_DATA:
            existing = db.query(Species).filter(
                Species.scientific_name_lower == data["scientific_name"].lower()
            ).first()

            if existing:
                skipped += 1
                print(f"  Skipped (exists): {data['scientific_name']}")
                continue

            species = Species(
                id=uuid.uuid4(),
                scientific_name_lower=data["scientific_name"].lower(),
                **data,
            )
            db.add(species)
            added += 1
            print(f"  Added: {data['scientific_name']}")

        db.commit()
        print(f"\nDone! Added {added}, skipped {skipped} (already existed).")

    except Exception as e:
        print(f"Error: {e}")
        db.rollback()
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed()
